### ISSUE TITLE
Install virtualbox extension pack

### ISSUE THREAD

**Issue by fazlearefin** [fazlearefin/ubuntu-dev-machine-setup#21]
Oracle tries to make sure you read and agree to their awesome license agreement before installing the package. This makes it difficult for automated installs. Sample code below needs to be integrated in the playbooks:

```yaml
- block:
  - name: accept licence virtualbox ext pack
    debconf:
      name: "virtualbox-ext-pack"
      question: "virtualbox-ext-pack/license"
      value: "true"
      vtype: "select"

  - name: install virtualbox ext pack
    apt:
      name: "virtualbox-ext-pack"

  when: not virtual_machine_mode
```
