### ISSUE TITLE
Install burp suite

### ISSUE THREAD

**Issue by fazlearefin** [fazlearefin/ubuntu-dev-machine-setup#73]
Sample playbook:

```yaml
---
- hosts: all
  become: yes
  tasks:

    - name: Install required dependencies
      apt:
        name:
          - openjdk-11-jre
        state: present
        update_cache: yes

    - name: Download Burp Suite Community Edition
      get_url:
        url: https://portswigger.net/burp/releases/download?product=community&type=linux
        dest: /tmp/burpsuite_community_linux.sh
        mode: 0755

    - name: Install Burp Suite Community Edition
      command: /tmp/burpsuite_community_linux.sh --prefix=/opt/burpsuite

    - name: Create symbolic link for Burp Suite
      file:
        src: /opt/burpsuite/burpsuite_community.sh
        dest: /usr/local/bin/burpsuite
        state: link

    - name: Create Burp Suite desktop entry
      copy:
        content: |
          [Desktop Entry]
          Name=Burp Suite Community Edition
          Exec=/opt/burpsuite/burpsuite_community.sh
          Terminal=false
          Type=Application
          Categories=Development;
        dest: /usr/share/applications/burpsuite.desktop
        mode: 0644
```
